#!/usr/bin/env ruby

require 'optparse'
require 'yaml'
require 'csv'
# require 'debugger'

require_relative 'lib/indexes'
require_relative 'lib/columns'
require_relative 'lib/command'

tables, errors, copy_selects = Columns.create_table_statements(CONF)
indexes = Indexes.create_index_statements(CONF)

#
# Report
#
errors.each {|e| $stderr.puts e}
exit 1 if errors.any?

# Print SQL to stdout
puts tables
indexes.each {|idx| puts idx }
puts copy_selects
